#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: factseeker
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: none
#    defer-datasource-initialization: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  output:
    ansi:
      enabled: always

jwt:
  secret: r13e07bVRWMPRVFy1kvbw9ZwBt5RbDOeLbzSNPj/C/juwI0R3ZMykXsD9Hzq2PLtnu2TtTk7YHCQpsazTc/Nqw== #빠른 시일 내에 환경변수로 등록 예정, 가능한 각자 환경변수에 저장하길 바람
  access-token-expiration-milliseconds: 3600000
  refresh-token-expiration-milliseconds: 604800000