# 공통 설정만 남기고, 민감값/환경별 값은 프로필로 분리
spring:
  mvc:
    async:
      request-timeout: 370000
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # dev/prod에서 필요 시 오버라이드
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name, email, phone_number
            redirect-uri: ${OAUTH_NAVER_REDIRECT_URI:http://localhost:8080/oauth2/callback/naver}
            authorization-grant-type: authorization_code
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: profile_nickname
            redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI:http://localhost:8080/oauth2/callback/kakao}
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# 앱 공통
app:
  mail:
    from: ${spring.mail.username}

oauth2:
  authorized-redirect-uris: ${OAUTH2_AUTHORIZED_REDIRECT_URIS:http://localhost:3000}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-milliseconds: 900000   # 15분
  refresh-token-expiration-milliseconds: 604800000 # 7일

youtube:
  api:
    key: ${YOUTUBE_API_KEY}

# EC2_IP 대신 완전한 URL로 받도록 정리
fastapi:
  base-url: ${FASTAPI_BASE_URL:http://localhost:8000}
  trends-url: ${TRENDS_URL:http://localhost:8000}

# LLM 설정 (ENV로 주입)
llm:
  openai:
    api-key: ${OPENAI_API_KEY}
    model: gpt-4o
    max-tokens: 2000
    temperature: 0.7
  gemini:
    api-key: ${GOOGLE_GEMINI_API_KEY}
    model: gemini-1.5-flash
    max-tokens: 2000
    temperature: 0.7

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.factseekerbackend
  paths-to-match: /api/**

  # Naver API settings
naver:
  base-url: https://openapi.naver.com
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}