spring:
  datasource:
    url: jdbc:mysql://db-user.c9a4eek04eqi.ap-northeast-2.rds.amazonaws.com:3306/userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: factseeker12

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  output:
    ansi:
      enabled: always