version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: factseeker-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - factseeker-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  factseeker-backend:
    image: "${DOCKERHUB_USERNAME}/factseeker-backend:latest"
    container_name: factseeker-backend
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - factseeker-network
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8080/actuator/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data:

networks:
  factseeker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
