version: '3.8'

services:
  factseeker-backend:
    image: jjjsukwoo/factseeker-backend:latest
    container_name: factseeker-backend
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - factseeker-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8080/actuator/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  nginx:
    image: nginx:alpine
    container_name: factseeker-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - factseeker-backend
    networks:
      - factseeker-network
    profiles: [production]

networks:
  factseeker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16